### ISSUE TITLE
Cannot init ACE3DSPlus and r4isdhc.hk from RAW

### ISSUE THREAD

**Issue by R-YaTian** [DS-Homebrew/ntrboot_flasher_nds#2]
ACE3DSPlus when loaded from itself works all fine. But when running on DSiMode, it cannot init from RAW.
Init failed on "tryBlowfishKey"...

The flashcart_core only support init r4isdhc.hk from RAW. But when running on DSiMode, it failed on "trySecureInit".
I try to send command to the cart, it always return 0x00000000...

Edit: The carts init all success using [ntrboot_flasher](https://github.com/ntrteam/ntrboot_flasher) on 3DS console...

**Comment by lifehackerhansol** [comment]
It's possible that carts may not be in RAW state. I haven't figured out a way to reliably find out if it is or not, though.

**Comment by lifehackerhansol** [comment]
Seems other carts that require init from RAW also do not work (i.e. timebomb carts.) Definitely an issue with the initialization step.

@R-YaTian does r4isdhc.hk also not init from RAW? I'm not exactly understanding your message.

**Comment by R-YaTian** [comment]
> Seems other carts that require init from RAW also do not work (i.e. timebomb carts.) Definitely an issue with the initialization step.
> 
> @R-YaTian does r4isdhc.hk also not init from RAW? I'm not exactly understanding your message.

Timebomb carts work all fine with RAW state on my side iirc. But r4isdhc.hk will not init from RAW.
